import { FaCheck } from "react-icons/fa";

const Items = [
  {
    id: 1,
    title: "PAKET MAINTENACE",
    subtitle: <strong style={{ color: "#43A8EB" }}>Laptop Standart Series</strong>,
    label: "Rp.",
    price: "100K",
    diskon: "250K",
    icon: <FaCheck />,
    description: "Pengerjaan 45 menit \nMenggunakan Thermal Pasta Terbaik \n Pembersihan FAN \n Pembersihan Keyboard \n Pembersihan Case",
    category: "laptop",
  },
  {
    id: 2,
    title: "PAKET MAINTENACE",
    subtitle: <strong style={{ color: "#43A8EB" }}>Laptop Gaming Series</strong>,
    label: "Rp.",
    price: "300K",
    diskon: "450K",
    icon: <FaCheck />,
    description: "Pengerjaan 45 menit \nMenggunakan Thermal Pasta Terbaik \n Pembersihan FAN \n Pembersihan Keyboard \n Pembersihan Case",
    category: "laptop",
  },
  {
    id: 3,
    title: "PAKET MAINTENACE",
    subtitle: <strong style={{ color: "#43A8EB" }}>Laptop Ultrabook Series</strong>,
    label: "Rp.",
    price: "250K",
    diskon: "350K",
    icon: <FaCheck />,
    description: "Pengerjaan 45 menit \nMenggunakan Thermal Pasta Terbaik \n Pembersihan FAN \n Pembersihan Keyboard \n Pembersihan Case",
    category: "laptop",
  },
  {
    id: 4,
    title: "PAKET MAINTENACE",
    subtitle: <strong style={{ color: "#43A8EB" }}>Laptop Bawa Thermal Sendiri</strong>,

    price: "100K",
    diskon: "250K",
    icon: <FaCheck />,
    description: "Pengerjaan 45 menit \nMenggunakan Thermal Pasta Terbaik \n Pembersihan FAN \n Pembersihan Keyboard \n Pembersihan Case",
    category: "laptop",
  },
  {
    id: 5,
    title: "PAKET REINSTALL WINDOWS",
    subtitle: <strong style={{ color: "#43A8EB" }}>Windows 7 AIO</strong>,
    label: "Rp.",
    price: "100K",
    diskon: "150K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll)\n Lengkap Driver \n Garansi 1 Bulan ",
    category: "laptop",
  },
  {
    id: 6,
    title: "PAKET REINSTALL WINDOWS",
    subtitle: <strong style={{ color: "#43A8EB" }}>Windows 8 AIO</strong>,
    label: "Rp.",
    price: "100K",
    diskon: "150K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll)\n Lengkap Driver \n Garansi 1 Bulan ",
    category: "laptop",
  },
  {
    id: 7,
    title: "PAKET REINSTALL WINDOWS",
    subtitle: <strong style={{ color: "#43A8EB" }}>Windows 10 AIO</strong>,
    label: "Rp.",
    price: "150K",
    diskon: "250K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll)\n Lengkap Driver \n Garansi 1 Bulan ",
    category: "laptop",
  },
  {
    id: 8,
    title: "PAKET REINSTALL WINDOWS",
    subtitle: <strong style={{ color: "#43A8EB" }}>Windows 11 AIO</strong>,
    label: "Rp.",
    price: "200K",
    diskon: "300K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll)\n Lengkap Driver \n Garansi 1 Bulan ",
    category: "laptop",
  },

  {
    id: 7,
    title: "PAKET REINSTALL LINUX",
    subtitle: <strong style={{ color: "#43A8EB" }}>ALL DISTRO LINUX</strong>,
    label: "Rp.",
    price: "200K",
    diskon: "300K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll) \n Garansi 1 Bulan ",
    category: "laptop",
  },
  {
    id: 8,
    title: "PAKET REINSTALL OSX MAC",
    subtitle: <strong style={{ color: "#43A8EB" }}>ALL MAC OSX</strong>,
    label: "Rp.",
    price: "250K",
    diskon: "350K",
    icon: <FaCheck />,
    description: "Pengerjaan 1-2 jaman \n Free Apps STD (Office, Chrome, Firefox,Adobe Pdf, Ms Office,Dll) \n Garansi 1 Bulan ",
    category: "laptop",
  },
  {
    id: 10,
    title: "PERBAIKAN MESIN",
    subtitle: <strong style={{ color: "#43A8EB" }}>ALL KERUSAKAN</strong>,
    price: "CALL US",
    diskon: "x.xxxK",
    icon: <FaCheck />,
    description:
      "MATI TOTAL \n NO DISPLAY \n DLL ",
      category: "laptop",
  },
  {
    id: 11,
    title: "PERBAIKAN SPAREPART DAN UPGRADE",
    subtitle: <strong style={{ color: "#43A8EB" }}>ALL SERIES LAPTOP ALL BRAND LAPTOP</strong>,
    price: "CALL US",
    diskon: "xxxK",
    icon: <FaCheck />,
    description:
      "Ganti Keyboard \n Ganti LCD \n Ganti Hardisk & SSD \n Ganti Bettrey \n Dan Sparepart Lainnya",
      category: "laptop",
  },
  {
    id: 12,
    title: "PAKET CORPORATE",
    subtitle: "(Ideal Untuk Instansi & Perusahaan)",
    price: "CALL US",
    diskon: "x.xxxK",
    icon: <FaCheck />,
    description:
      "Domain .com / .id / .co.id \n SSL Certificate \n Kapasitas 40GB (Private Hosting) \n 30+ Email Profesional \n Request Desain Website \n 20+ Halaman Website \n Full Akses Admin & cPanel \n 5x Revisi Desain \n Otentikasi social media (Facebook & Gmail Login Register) \n Sales Popup \n Notifikasi (Email/SMS/Whatsapp) \n Progressive Web App (Aplikasi Mobile) \n Gratis Video Tutorial & Pelatihan \n ptimasi SEO on Page, Integrasi Google Webmaster, Google Analytics, & Facebook Pixel \n Gratis Konsultasi Optimasi & Digital Marketing \n Garansi Seumur Hidup*",
    // category: "companyprofile",
  },
];

export default Items;
